name: Python check (Linux)
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  cpptests:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    name: Python build flags
    runs-on: ${{ matrix.os }}

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/setup-python@v4
        name: Install Python 3.7
        with:
          python-version: '3.7'

      - name: Check args Python 3.7
        run: |
          python -c "import sysconfig; print(sysconfig.get_config_vars()['CONFIG_ARGS'])"

      - uses: actions/setup-python@v4
        name: Install Python 3.8
        with:
          python-version: '3.8'

      - name: Check args Python 3.8
        run: |
          python -c "import sysconfig; print(sysconfig.get_config_vars()['CONFIG_ARGS'])"


      - uses: actions/setup-python@v4
        name: Install Python 3.9
        with:
          python-version: '3.9'

      - name: Check args Python 3.9
        run: |
          python -c "import sysconfig; print(sysconfig.get_config_vars()['CONFIG_ARGS'])"


      - uses: actions/setup-python@v4
        name: Install Python 3.10
        with:
          python-version: '3.10'

      - name: Check args Python 3.10
        run: |
          python -c "import sysconfig; print(sysconfig.get_config_vars()['CONFIG_ARGS'])"