name: Testing on Windows
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cpptests:
    name: C++ tests (Windows)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2

      - name: Configure MSVC for amd64 # Use cl.exe as a default compiler
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Build and run unit tests
        run: |
            cmake . -BBuild  -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DENABLE_OPENMP=OFF -DENABLE_WARNINGS=OFF
            cmake --build ./Build
            mkdir -p ./Build/tests/results
            .\Build\pennylane_lightning\src\tests\Debug\runner.exe --order lex --reporter junit --out .\Build\tests\results\report.xml

      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: windows-test-report
          path: .\Build\tests\results\report.xml
